### ISSUE TITLE
[Basic] Crafting Recipes Broken

### ISSUE THREAD

**Issue by Eearslya** [Shad0wB1ade/Solar-Expansion-Lang#7]
I just installed the brand new FTB Infinity modpack, which includes version 1.4d of Solar Expansion.

The only issue is that the crafting for the Hardened Solar Panel got mixed up somehow. The recipe is broken such that the Hardened Solar Panel requires Hardened Solar Panels to craft, thus making it impossible to make any panels above Leadstone.

I'm uncertain if this is an issue with the pack or with your mod, we are using FastCraft if that means anything.

http://imgur.com/2wB8FEO

**Comment by Shad0wB1ade** [comment]
That was a little opssy on my part... I was cleaning up code and messed up there. Sorry. Fixed. I hope the FTB team gets the build soon.
