### ISSUE TITLE
[BASIC] Crash Log

### ISSUE THREAD

**Issue by MrBretze** [Shad0wB1ade/Solar-Expansion-Lang#8]
a crash report (unload chunk) http://paste.md-5.net/debidusuce.avrasm

**Comment by Shad0wB1ade** [comment]
Please read through https://github.com/Shad0wB1ade/Solar-Expansion-Lang#contributing before reporting bugs >.<

**Comment by MrBretze** [comment]
Forge Version 10.13.2.1291
TE: ThermalExpansion-[1.7.10]4.0.0RC2-129
TDY: ThermalDynamics-[1.7.10]1.0.0RC2-77
CoFHCore: CoFHCore-[1.7.10]3.0.0RC2-195
CoFHLib: CoFHLib-[1.7.10]1.0.0B9-118

I just ask a dynamic thermal cable and when you load / unload the chunk there are crash in a vore related connsole mods.

**Comment by Shad0wB1ade** [comment]
*facepalm* I need to know what version of Solar Expansion you are using.

**Comment by MrBretze** [comment]
SolarExpansion-Basic-1.4c

**Comment by Shad0wB1ade** [comment]
Does the same thing happen with 1.4e? because I was not able to replicate that bug.

**Comment by MrBretze** [comment]
You have tested to a spawn world ?

**Comment by MrBretze** [comment]
1.4e no crafting ?

**Comment by Shad0wB1ade** [comment]
what do you mean?

**Comment by MrBretze** [comment]
with the mod not enought i cant see the recipe of solar panel (SolarExpansion-Basic-1.4e)

**Comment by Shad0wB1ade** [comment]
Ok I'm aware of the recipe bug... it must be a derp in my code somewhere. I will fix that... its no big deal, but is the bug still happening?

**Comment by MrBretze** [comment]
Not the bug looks eter set (I is not tested on server and on the main world)

**Comment by Shad0wB1ade** [comment]
Ok I will fix everything soon ;) just check tommorow or on sunday on my forum in the last page in the comments and download 1.4f. I hope to get it released at least :P

**Comment by MrBretze** [comment]
no update in curseforge ?

**Comment by Shad0wB1ade** [comment]
I didn't have time to test so for now updates will be in the comments in my forum... when I feel comfortable making a release I will upload the update to curseforge.

**Comment by MrBretze** [comment]
Ok
