### ISSUE TITLE
[ALL] [IDEA] Waila

### ISSUE THREAD

**Issue by MrBretze** [Shad0wB1ade/Solar-Expansion-Lang#9]
Adding Waila in Solar expention ? (see RF/t product / stored)

**Comment by Shad0wB1ade** [comment]
Well waila already works with Solar Expansion and it shows you the energy stored. I've tested it in my costume pack and FTB Infinity.

**Comment by MrBretze** [comment]
Version f ?

**Comment by Shad0wB1ade** [comment]
even 1.4c works

**Comment by MrBretze** [comment]
its not working in c

**Comment by Shad0wB1ade** [comment]
idk it works for me in all versions (I have latest cofh mods and latest waila)

**Comment by MrBretze** [comment]
No for me http://puu.sh/gi31P/d12e4ad4b9.jpg i use the latest cofh mods and waila

**Comment by Shad0wB1ade** [comment]
I have no idea why o.o

**Comment by Shad0wB1ade** [comment]
I just downloaded the latest version of CoFH stuff and waila and the energy shows >.< I have no idea what is going on

**Comment by MrBretze** [comment]
I use this mods pack http://www.technicpack.net/modpack/retraite-of-gaming.574675

**Comment by Shad0wB1ade** [comment]
Try updating to the latest version of waila (1.5.10-1.7.10) and tell me if you have problems with the power thing. For now I am going to close this issue but if you have any problem with waila tell me and I will fix/reopen the issue.
